;;; org-async.el --- Async Init.el File for Org Export  -*- lexical-binding: t; -*-

;; Copyright (C) 2024

;; Author:  <divya@alberteinstein>
;; Keywords: lisp, tex

(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

(setq load-path '("/home/divya/.emacs.d/straight/build/biblio-core"
 "/home/divya/.emacs.d/straight/build/biblio"
 "/home/divya/.emacs.d/straight/build/gcmh"
 "/home/divya/.emacs.d/straight/build/eshell-git-prompt"
 "/home/divya/.emacs.d/straight/build/shell-pop"
 "/home/divya/.emacs.d/straight/build/popon"
 "/home/divya/.emacs.d/straight/build/corfu-terminal"
 "/home/divya/.emacs.d/straight/build/corfu"
 "/home/divya/.emacs.d/straight/build/yaml"
 "/home/divya/.emacs.d/straight/build/treepy"
 "/home/divya/.emacs.d/straight/build/ghub"
 "/home/divya/.emacs.d/straight/build/closql"
 "/home/divya/.emacs.d/straight/build/forge"
 "/home/divya/.emacs.d/straight/build/magit"
 "/home/divya/.emacs.d/straight/build/js2-mode"
 "/home/divya/.emacs.d/straight/build/skewer-mode"
 "/home/divya/.emacs.d/straight/build/htmlize"
 "/home/divya/.emacs.d/straight/build/impatient-mode"
 "/home/divya/.emacs.d/straight/build/web-mode"
 "/home/divya/.emacs.d/straight/build/helpful"
 "/home/divya/.emacs.d/straight/build/elisp-refs"
 "/home/divya/.emacs.d/straight/build/scheme-complete"
 "/home/divya/.emacs.d/straight/build/rainbow-delimiters"
 "/home/divya/.emacs.d/straight/build/macrostep"
 "/home/divya/.emacs.d/straight/build/slime"
 "/home/divya/.emacs.d/straight/build/paren-face"
 "/home/divya/.emacs.d/straight/build/paredit"
 "/home/divya/.emacs.d/straight/build/pollen-mode"
 "/home/divya/.emacs.d/straight/build/racket-mode"
 "/home/divya/.emacs.d/straight/build/geiser-guile"
 "/home/divya/.emacs.d/straight/build/geiser-chez"
 "/home/divya/.emacs.d/straight/build/geiser-mit"
 "/home/divya/.emacs.d/straight/build/forth-mode"
 "/home/divya/.emacs.d/straight/build/rust-mode"
 "/home/divya/.emacs.d/straight/build/haskell-mode"
 "/home/divya/.emacs.d/straight/build/go-mode"
 "/home/divya/.emacs.d/straight/build/eldoc-box"
 "/home/divya/.emacs.d/straight/build/rmsbolt"
 "/home/divya/.emacs.d/straight/build/color-identifiers-mode"
 "/home/divya/.emacs.d/straight/build/symbol-overlay"
 "/home/divya/.emacs.d/straight/build/soap-client"
 "/home/divya/.emacs.d/straight/build/debbugs"
 "/home/divya/.emacs.d/straight/build/with-editor"
 "/home/divya/.emacs.d/straight/build/ess/obsolete"
 "/home/divya/.emacs.d/straight/build/ess"
 "/home/divya/.emacs.d/straight/build/elgrep"
 "/home/divya/.emacs.d/straight/build/fzf"
 "/home/divya/.emacs.d/straight/build/el-easydraw"
 "/home/divya/.emacs.d/straight/build/empv"
 "/home/divya/.emacs.d/straight/build/emacs-everywhere"
 "/home/divya/.emacs.d/straight/build/let-alist"
 "/home/divya/.emacs.d/straight/build/markdown-mode"
 "/home/divya/.emacs.d/straight/build/sx"
 "/home/divya/.emacs.d/straight/build/anki-editor"
 "/home/divya/.emacs.d/straight/build/elfeed-org"
 "/home/divya/.emacs.d/straight/build/elfeed"
 "/home/divya/.emacs.d/straight/build/stripes"
 "/home/divya/.emacs.d/straight/build/djvu"
 "/home/divya/.emacs.d/straight/build/kv"
 "/home/divya/.emacs.d/straight/build/esxml"
 "/home/divya/.emacs.d/straight/build/nov"
 "/home/divya/.emacs.d/straight/build/org-noter"
 "/home/divya/.emacs.d/straight/build/consult-dir"
 "/home/divya/.emacs.d/straight/build/dired-hacks-utils"
 "/home/divya/.emacs.d/straight/build/dired-subtree"
 "/home/divya/.emacs.d/straight/build/dired-sidebar"
 "/home/divya/.emacs.d/straight/build/dired-rsync"
 "/home/divya/.emacs.d/straight/build/dirvish"
 "/home/divya/.emacs.d/straight/build/fd-dired"
 "/home/divya/.emacs.d/straight/build/aio"
 "/home/divya/.emacs.d/straight/build/xenops"
 "/home/divya/.emacs.d/straight/build/yasnippet"
 "/home/divya/.emacs.d/straight/build/cdlatex"
 "/home/divya/.emacs.d/straight/build/auctex"
 "/home/divya/.emacs.d/straight/build/flymake-proselint"
 "/home/divya/.emacs.d/straight/build/langtool"
 "/home/divya/.emacs.d/straight/build/org-alert"
 "/home/divya/.emacs.d/straight/build/svg"
 "/home/divya/.emacs.d/straight/build/org-timeblock"
 "/home/divya/.emacs.d/straight/build/org-journal"
 "/home/divya/.emacs.d/straight/build/consult-org-roam"
 "/home/divya/.emacs.d/straight/build/wgrep"
 "/home/divya/.emacs.d/straight/build/rg"
 "/home/divya/.emacs.d/straight/build/websocket"
 "/home/divya/.emacs.d/straight/build/simple-httpd"
 "/home/divya/.emacs.d/straight/build/org-roam-ui"
 "/home/divya/.emacs.d/straight/build/magit-section"
 "/home/divya/.emacs.d/straight/build/emacsql"
 "/home/divya/.emacs.d/straight/build/org-roam"
 "/home/divya/.emacs.d/straight/build/org-present"
 "/home/divya/.emacs.d/straight/build/org-make-toc"
 "/home/divya/.emacs.d/straight/build/toc-org"
 "/home/divya/.emacs.d/straight/build/org-modern"
 "/home/divya/.emacs.d/straight/build/org-appear"
 "/home/divya/.emacs.d/straight/build/citar-embark"
 "/home/divya/.emacs.d/straight/build/string-inflection"
 "/home/divya/.emacs.d/straight/build/queue"
 "/home/divya/.emacs.d/straight/build/citeproc"
 "/home/divya/.emacs.d/straight/build/parsebib"
 "/home/divya/.emacs.d/straight/build/citar"
 "/home/divya/.emacs.d/straight/build/transient"
 "/home/divya/.emacs.d/straight/build/peg"
 "/home/divya/.emacs.d/straight/build/ov"
 "/home/divya/.emacs.d/straight/build/ts"
 "/home/divya/.emacs.d/straight/build/org-super-agenda"
 "/home/divya/.emacs.d/straight/build/org"
 "/home/divya/.emacs.d/straight/build/map"
 "/home/divya/.emacs.d/straight/build/org-ql"
 "/home/divya/.emacs.d/straight/build/edit-indirect"
 "/home/divya/.emacs.d/straight/build/magit-popup"
 "/home/divya/.emacs.d/straight/build/bui"
 "/home/divya/.emacs.d/straight/build/xref"
 "/home/divya/.emacs.d/straight/build/project"
 "/home/divya/.emacs.d/straight/build/geiser"
 "/home/divya/.emacs.d/straight/build/guix"
 "/home/divya/.emacs.d/straight/build/transpose-frame"
 "/home/divya/.emacs.d/straight/build/popper"
 "/home/divya/.emacs.d/straight/build/ace-window"
 "/home/divya/.emacs.d/straight/build/avy"
 "/home/divya/.emacs.d/straight/build/embark-consult"
 "/home/divya/.emacs.d/straight/build/embark"
 "/home/divya/.emacs.d/straight/build/expand-region"
 "/home/divya/.emacs.d/straight/build/meow"
 "/home/divya/.emacs.d/straight/build/undo-fu"
 "/home/divya/.emacs.d/straight/build/async"
 "/home/divya/.emacs.d/straight/build/org-download"
 "/home/divya/.emacs.d/straight/build/justify-kp"
 "/home/divya/.emacs.d/straight/build/dimmer"
 "/home/divya/.emacs.d/straight/build/solaire-mode"
 "/home/divya/.emacs.d/straight/build/dashboard"
 "/home/divya/.emacs.d/straight/build/consult"
 "/home/divya/.emacs.d/straight/build/orderless"
 "/home/divya/.emacs.d/straight/build/all-the-icons-completion"
 "/home/divya/.emacs.d/straight/build/marginalia"
 "/home/divya/.emacs.d/straight/build/vertico"
 "/home/divya/.emacs.d/straight/build/visual-fill-column"
 "/home/divya/.emacs.d/straight/build/writeroom-mode"
 "/home/divya/.emacs.d/straight/build/which-key"
 "/home/divya/.emacs.d/straight/build/smartparens"
 "/home/divya/.emacs.d/straight/build/ht"
 "/home/divya/.emacs.d/straight/build/emojify"
 "/home/divya/.emacs.d/straight/build/ucs-utils"
 "/home/divya/.emacs.d/straight/build/list-utils"
 "/home/divya/.emacs.d/straight/build/pcache"
 "/home/divya/.emacs.d/straight/build/persistent-soft"
 "/home/divya/.emacs.d/straight/build/font-utils"
 "/home/divya/.emacs.d/straight/build/unicode-fonts"
 "/home/divya/.emacs.d/straight/build/f"
 "/home/divya/.emacs.d/straight/build/dash"
 "/home/divya/.emacs.d/straight/build/s"
 "/home/divya/.emacs.d/straight/build/shrink-path"
 "/home/divya/.emacs.d/straight/build/nerd-icons"
 "/home/divya/.emacs.d/straight/build/seq"
 "/home/divya/.emacs.d/straight/build/compat"
 "/home/divya/.emacs.d/straight/build/doom-modeline"
 "/home/divya/.emacs.d/straight/build/log4e"
 "/home/divya/.emacs.d/straight/build/gntp"
 "/home/divya/.emacs.d/straight/build/alert"
 "/home/divya/.emacs.d/straight/build/rainbow-mode"
 "/home/divya/.emacs.d/straight/build/ef-themes"
 "/home/divya/.emacs.d/straight/build/crux"
 "/home/divya/.emacs.d/straight/build/all-the-icons-dired"
 "/home/divya/.emacs.d/straight/build/all-the-icons"
 "/home/divya/.emacs.d/straight/build/bind-key"
 "/home/divya/.emacs.d/straight/build/use-package"
 "/home/divya/.emacs.d/straight/build/straight"
 "/home/divya/.config/guix/current/share/emacs/site-lisp"
 "/home/divya/.guix-home/profile/share/emacs/site-lisp"
 "/gnu/store/cpj3yc0f2ra3drhb3ma20f52lm9sck0y-emacs-pdf-tools-1.1.0/share/emacs/site-lisp/pdf-tools-1.1.0"
 "/gnu/store/mh2mc07z5m4m6qy69panlcrjh6vqrr08-emacs-tablist-1.1/share/emacs/site-lisp/tablist-1.1"
 "/gnu/store/b42asgqmryrdk7wfdd8b5m4pzv3n8972-emacs-saveplace-pdf-view-1.0.7/share/emacs/site-lisp/saveplace-pdf-view-1.0.7"
 "/home/divya/.guix-profile/share/emacs/site-lisp"
 "/run/current-system/profile/share/emacs/site-lisp"
 "/gnu/store/k98fwblkskv7bxw1kqrli8b9pnc7r1q6-mu-1.12.6/share/emacs/site-lisp/mu4e"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/vc"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/use-package"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/url"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/textmodes"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/progmodes"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/play"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/org"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/nxml"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/net"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/mh-e"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/mail"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/leim"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/language"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/international"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/image"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/gnus"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/eshell"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/erc"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/emulation"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/emacs-lisp"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/cedet"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/calendar"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/calc"
 "/gnu/store/hicgrdcmv63hq1lgpdrvd6nmn4cvz3mi-emacs-next-30.0.60-1.4e22ef8/share/emacs/30.0.60/lisp/obsolete"
 "/home/divya/.emacs.d/lisp/bookmark+"
 "/home/divya/.emacs.d/lisp/dired+" "/home/divya/.emacs.d/lisp/golden"
 "/home/divya/.emacs.d/lisp/hs-lint"
 "/home/divya/.emacs.d/lisp/password-store"))

(require 'org)
(require 'ox)

(require 'citar)

(setq org-cite-global-bibliography '("/mnt/LDisk-E/Albert Einstein/Books & Resources/Sociology/Gender Mainstreaming/Megha/thesis/chapters/gm-thesis.bib"))
			      ;; '("~/bib/neuroscience.bib")
			      ;; '("~/bib/divya-library.bib"))
(setq org-cite-insert-processor 'citar)
(setq org-cite-follow-processor 'citar)
(setq org-cite-activate-processor 'citar)
(setq citar-bibliography org-cite-global-bibliography)
(setq citar-org-styles-format 'short)

;; (require 'cl)
(setq org-export-async-debug nil)
