#!/bin/zsh

# Profile file that runs on login.

export BROWSER="librewolf"
export EDITOR="emacsclient -c"
export VIDEO="mpv"
export TERMINAL="alacritty"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export EINSTEIN="/mnt/LDisk-E/Albert Einstein/"
export RECORDING="$EINSTEIN/Recordings"
export PASSWORD_STORE_DIR="$HOME/life/passwords/pass/"
# export SSL_CERT_DIR="/etc/ssl/certs"

# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"


## PATH
if [ -d "$HOME/.bin" ] ;
then PATH="$HOME/.bin:$PATH"
fi

if [ -d "/root/.local/bin" ];
then PATH="/root/.local/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ;
then PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.cabal/bin" ];
then PATH="$HOME/.cabal/bin:$PATH"
fi

if [ -d "$HOME/Applications" ] ;
then PATH="$HOME/Applications:$PATH"
fi

if [ -d "/home/divya/.ghcup/bin" ] ;
then PATH="/home/divya/.ghcup/bin:$PATH"
fi

if [ -d "/home/divya/.cargo/bin" ] ;
then PATH="/home/divya/.cargo/bin:$PATH"
fi

if [ -d "/home/divya/.local/share/gem/ruby/3.0.0/bin" ] ;
then PATH="/home/divya/.local/share/gem/ruby/3.0.0/bin:$PATH"
fi

if [ -d "/home/divya/.radicle/bin" ] ;
then PATH="/home/divya/.radicle/bin:$PATH"
fi

if [ -d "/home/divya/.elan/bin" ] ;
then PATH="/home/divya/.elan/bin:$PATH"
fi
