#! /bin/bash


# Backing up notes
cp -rp '/home/divya/notes/' '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/'

# Compress
tar -cvzf '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/notes-latest.gz' /home/divya/notes/

# Encrypt it
gpg --encrypt --recipient divya '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/notes-latest.gz'   
