#! /bin/bash

# Backup life into several places
yes | cp -rp /home/divya/life '/mnt/LDisk-E/Albert Einstein/THE UNIVERSE/backup/'
yes | cp -rp /home/divya/life '/mnt/LDisk-D/'

# Bookmarks
yes | cp -p /home/divya/.dotfiles/.emacs.d/bookmarks /home/divya/life/bookmarks/emacs-bookmarks

# Backing up notes
yes | cp -rp '/home/divya/notes/' '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/'
yes | cp -rp '/home/divya/notes/' '/mnt/LDisk-D/'


# Compress
yes | tar -cvzf '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/notes-latest.gz' /home/divya/notes/

# Encrypt it
gpg --encrypt --recipient divya '/mnt/LDisk-E/Albert Einstein/Books & Resources/Notes/latest/notes-latest.gz'
