## Alacritty Configuration

[window]

opacity = 0.90
padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Victor Mono Medium"

size = 13.0

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[terminal.shell]
program = "/run/current-system/profile/bin/zsh"

# Scrollback
[scrolling]
history = 10000  # Number of lines in scrollback history
multiplier = 3

[general]
import = ["~/.config/alacritty/themes/themes/monokai_charcoal.toml"]

[terminal]

# [bell]
# command = "<string>" | { program = "<string>", args = ["<string>",] }